title: "Turning Ideas into Code"
author: "Joseph Won"
description: "Learn to be a better developer"
#subheading: "Really cool blog about ... something"
more: "read more"
url: "http://josephwondev.com"
baseurl: "/blog" # comment out if in root directory

comments:
    disqus: ""
#    isso: "comments.mysite.org"

style:
    body: "whitesmoke"
    padding: 33%
    anchor: "#46f"
    serif-heading: true
    nav: "#181818"
#    headline: "#06f"
    description: "white"
    article:
        odd: "#ffffff"
        even: "#222222"

links:
  - github: "https://github.com/godspeedyoo/"
  - twitter: "https://twitter.com/godspeedyoo/"

excerpt_separator: "\n\n\n"
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
